Add Shopaholic technology
AliasIO/wappalyzer pull request #5244
Opened 2021-11-17 08:20 UTC by FlusherDock1

Adding https://shopaholic.one/
This is extension for October CMS

2021-11-17 16:16 UTC, nurbek91 requested changes

2021-11-17 16:16 UTC, nurbek91 commented on src/technologies/s.json
> +    "dom": {
Hey mate, thanks for PR . Let's remove the` dom.`
And instead of it we will write:
```
"js": {
      "ShopaholicCart": ""
    },
```
example: https://babylon64.ru/

2021-11-17 16:16 UTC, nurbek91 commented on src/technologies/s.json
> +    "implies": [
\\;confidence:100" I think this is not needed here

2021-11-21 15:46 UTC, FlusherDock1 commented on src/technologies/s.json
> +    "implies": [
Why?

2021-11-21 15:46 UTC, FlusherDock1 commented on src/technologies/s.json
> +    "dom": {
I don' understand how your js section works.

2021-11-21 15:53 UTC, nurbek91 commented on src/technologies/s.json
> +    "dom": {
![image](https://user-images.githubusercontent.com/3456008/142769137-d3db37b9-3894-4256-be7b-ef369cfe7f5b.png)

2021-11-21 16:01 UTC, nurbek91 commented on src/technologies/s.json
> +    "implies": [
"requires": "October CMS", 
"implies": "October CMS\\;confidence:99", 
It doesn't look logical. I guess I'm finding fault. If there are no mistakes, you can leave

2021-11-21 20:10 UTC, merged

2021-11-21 20:10 UTC, AliasIO commented
I fixed it up, thank you!