add superhero
AliasIO/wappalyzer pull request #5339
Opened 2021-11-28 01:52 UTC by gemini133

2021-11-28 01:52 UTC, gemini133 commented
example site https://help.importify.com/

2021-11-28 16:21 UTC, nurbek91 requested changes
### Hey there thanks for PR. Some changes will be required
### examples:
**external link:**
https://home.by.me
https://www.freightos.com/
https://www.fluentify.com/
**Where does the link lead**:
https://fluentify.supporthero.io/login/signIn
**like widget:** 
https://www.toner.fr/
https://fluentify.supporthero.io/login/signIn
https://www.golfgenius.com/
https://cengage.com.au/

2021-11-28 16:21 UTC, nurbek91 commented on src/technologies/s.json
> +  "Super Hero": {
Change tech name to Support Hero.

2021-11-28 16:21 UTC, nurbek91 commented on src/technologies/s.json
> +    "description": "Super Hero is a knowledge base solution to reduce inbound support requests.",
Support Hero is a knowledge base solution to reduce inbound support requests.

2021-11-28 16:21 UTC, nurbek91 commented on src/technologies/s.json
> +    "icon": "superhero.png",
Support Hero.png

2021-11-28 16:21 UTC, nurbek91 commented on src/technologies/s.json
> +    "icon": "superhero.png",
Add pricing:
```
"saas": true,
    "pricing": [
      "mid",
      "recurring"
    ],
```

2021-11-28 16:21 UTC, nurbek91 commented on src/technologies/s.json
> +    "html": [
Lets remove` html` and use `js` and` dom`:
```
"js": {
      "supportHeroWidget": "",
      "supporthero": ""
    },
"dom": "a[href*='.supporthero.io/'][target='_blank']"
```

2021-11-29 00:47 UTC, gemini133 commented
thanks for your help. all resolved!

2021-11-29 02:55 UTC, merged

2021-11-29 02:55 UTC, AliasIO commented
Thanks!