Add quicq detection
AliasIO/wappalyzer pull request #5579
Opened 2022-02-04 11:06 UTC by gijsbotje

adds quicq detection

quicq is an image optimization tool built by Afosto

2022-02-04 14:53 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!
Small updates required to be merged

2022-02-04 14:53 UTC, nurbek91 commented on src/technologies/q.json
> +    ],
Let's use one category 
92 (Performance) 
Also  we can leave 31(CDN) probably

2022-02-04 14:53 UTC, nurbek91 commented on src/technologies/q.json
> +    ],
I think it will suffice to indicate these
```
"freemium",
"payg"
```

2022-02-04 14:53 UTC, nurbek91 commented on src/technologies/q.json
> +    "description": "The perfect image for all visitors and devices. Quicq's smart technology automatically switches between different next-gen image formats based on the visitor's device.",
Something like this.
"description": "Quicq is an image optimisation app by Afosto.",

2022-02-04 14:53 UTC, nurbek91 commented on src/icons/Afosto.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42 48"><g fill="none"><path fill="#04A54F" d="M41.48 35.9v11.83l-9.83-6.1"/><path fill="#2F3B60" d="M41.45 35.9l-20.7 11.96V23.94"/><path fill="#1
Do we need an Afosto icon at this stage

2022-02-04 14:53 UTC, nurbek91 commented on src/apps.json
> +{
Do we need this file? It should probably be removed too.

2022-02-04 14:58 UTC, nurbek91 commented
And the last request, could you share with examples in the PR description

2022-02-07 08:23 UTC, gijsbotje commented on src/icons/Afosto.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42 48"><g fill="none"><path fill="#04A54F" d="M41.48 35.9v11.83l-9.83-6.1"/><path fill="#2F3B60" d="M41.45 35.9l-20.7 11.96V23.94"/><path fill="#1
Afosto itself is for detecting ecommerce sites built with our main software. Quicq is a tool we created for our users and others that don't use our ecommerce software.

2022-02-07 08:34 UTC, gijsbotje commented
@nurbek91 updated the branch, sorry did it from an old master branch. Should be good now.
Also added examples.

2022-02-09 00:04 UTC, merged

2022-02-09 00:04 UTC, AliasIO commented
Thanks!