Add Super.so detection
AliasIO/wappalyzer pull request #5713
Opened 2022-03-13 09:26 UTC by ysm0622

website:
- https://super.so

examples: https://super.so/showcase

- https://learn.rainbow.me/
- https://nathanclark.net/
- https://docs.basedash.com/
- https://bensomething.com/
- https://sofahq.super.site/
- https://docs.spline.design/

2022-03-13 16:09 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!!!
Minor changes are required to bring your request to the ideal.

2022-03-13 16:09 UTC, nurbek91 commented on src/technologies/s.json
> +    "dom": "div.super-content",
https://www.europafm.com/ 
One question on the pattern. Is this site built with this technology.
If not, then you can probably leave it, or use other options like link and img[srcset]

2022-03-13 18:01 UTC, ysm0622 commented on src/technologies/s.json
> +  "Super.so": {
[664c56e](https://github.com/AliasIO/wappalyzer/pull/5713/commits/664c56ed76a6e0fd220d7440773725cf789d7373)

2022-03-13 18:01 UTC, ysm0622 commented on src/technologies/s.json
> +    "description": "Build websites with Notion.",
[664c56e](https://github.com/AliasIO/wappalyzer/pull/5713/commits/664c56ed76a6e0fd220d7440773725cf789d7373)

2022-03-13 18:01 UTC, ysm0622 commented on src/technologies/s.json
> +    "icon": "super.so.png",
[664c56e](https://github.com/AliasIO/wappalyzer/pull/5713/commits/664c56ed76a6e0fd220d7440773725cf789d7373)

2022-03-13 18:01 UTC, ysm0622 commented on src/technologies/s.json
> +      "freemium"
[664c56e](https://github.com/AliasIO/wappalyzer/pull/5713/commits/664c56ed76a6e0fd220d7440773725cf789d7373)

2022-03-13 18:02 UTC, ysm0622 commented on src/technologies/s.json
> +    "dom": "div.super-content",
[664c56e](https://github.com/AliasIO/wappalyzer/pull/5713/commits/664c56ed76a6e0fd220d7440773725cf789d7373)

I'm not sure for this. but is it enough? 🤔

```json
    "dom": "link[href*='https://super-static-assets.s3.amazonaws.com']",
```

2022-03-14 04:46 UTC, ysm0622 commented on src/technologies/s.json
> +    "dom": "div.super-content",
@nurbek91

2022-03-14 05:26 UTC, nurbek91 commented on src/technologies/s.json
> +    "dom": "div.super-content",
"dom": "link[href*='super-static-assets\\.'],   img[srcset*='super-static-assets\\.']",
Hey @ysm0622 , something like this, couldnt test , currently i am not at the pc

2022-03-14 06:47 UTC, ysm0622 commented on src/technologies/s.json
> +    "dom": "div.super-content",
@nurbek91 [0ad296a](https://github.com/AliasIO/wappalyzer/pull/5713/commits/0ad296a37e1e54d9ef6bed3374092d7877f8b148)

2022-03-14 06:53 UTC, nurbek91 approved these changes
Hey, thanks!!!

2022-03-14 07:05 UTC, ysm0622 commented
@nurbek91 Thank you for your kind review. 🙏🏻

2022-03-15 01:02 UTC, merged

2022-03-15 01:02 UTC, AliasIO commented
Thanks!